baseURL = "https://lafermetteverdoyante.com/"
############################# Outputs ##############################
[outputs]
home = ["HTML", "WebAppManifest"]

############################ Media types ############################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

############################ Output Format ###########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"   

[module]
  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/seo-tools/matomo-analytics"   