[params]
logo = "images/logo.png"
logo_darkmode = "images/logo-darkmode.png"

############################# Outputs ##############################
[outputs]
home = ["WebAppManifest"]

############################ Media types ############################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

############################ Output Format ###########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"   