############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "À Propos"
url = "/about"
weight = 2

[[main]]
name = "Elements"
url = "/elements"
weight = 3

[[main]]
weight = 4
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
url = "/blog"

[[main]]
parent = "Pages"
name = "Contact"
url = "/contact"

[[main]]
parent = "Pages"
name = "Auteurs"
url = "/authors"

[[main]]
parent = "Pages"
name = "Catégories"
url = "/categories"

[[main]]
parent = "Pages"
name = "404 Page"
url = "/404"


# pied de page menu
[[footer]]
name = "À Propos"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Vie privée"
url = "/privacy-policy"
weight = 3
