############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "Calendrier"
url = "/event"
weight = 2

[[main]]
name = "Activités"
weight = 3

[[main]]
parent = "Activités"
name = "Méthodes de culture"
url = "/culture"

[[main]]
parent = "Activités"
name = "Gestion des récoltes"
url = "/recolte"

[[main]]
parent = "Activités"
name = "Gestion de l'eau"
url = "/eau"

[[main]]
parent = "Activités"
name = "L'outil domotique"
url = "/domotique"

[[main]]
weight = 4
name = "Blog"
url = "/blog"

[[main]]
weight = 5
name = "Contact"
url = "/contact"

# pied de page menu
[[footer]]
name = "À Propos"
url = "/about"
weight = 1

[[footer]]
name = "Vie privée"
url = "/privacy-policy"
weight = 2

[[footer]]
name = "Auteurs"
url = "/authors"
weight = 3

[[footer]]
name = "Elements"
url = "/elements"
weight = 4