############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Visits & Workshops"
weight = 2

[[main]]
parent = "Visits & Workshops"
name = "Visits"
url = "/visits"

[[main]]
parent = "Visits & Workshops"
name = "Workshops"
url = "/workshops"

[[main]]
parent = "Visits & Workshops"
name = "Calendar"
url = "/calendar"

[[main]]
name = "Site Activities"
weight = 3

[[main]]
parent = "Site Activities"
name = "Cultivation Methods"
url = "/culture"

[[main]]
parent = "Site Activities"
name = "Harvest Management"
url = "/harvest"

[[main]]
parent = "Site Activities"
name = "Water Management"
url = "/water"

[[main]]
parent = "Site Activities"
name = "Home Automation"
url = "/automation"

#[[main]]
#weight = 5
#name = "Blog"
#url = "/blog"

[[main]]
weight = 6
name = "Contact Us"
url = "/contact"

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Privacy"
url = "/privacy-policy"
weight = 2

[[footer]]
name = "Legal Notices"
url = "/mentions"
weight = 3

[[footer]]
name = "Contact Us"
url = "/contact"
weight = 4

#[[footer]]
#name = "Elements"
#url = "/elements"
#weight = 5