############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "Visites & Ateliers"
weight = 2

[[main]]
parent = "Visites & Ateliers"
name = "Visites"
url = "/visites"

[[main]]
parent = "Visites & Ateliers"
name = "Ateliers"
url = "/ateliers"

[[main]]
parent = "Visites & Ateliers"
name = "Calendrier"
url = "/calendrier"

[[main]]
name = "Activités du lieu"
weight = 3

[[main]]
parent = "Activités du lieu"
name = "Méthodes de culture"
url = "/culture"

[[main]]
parent = "Activités du lieu"
name = "Gestion des récoltes"
url = "/recolte"

[[main]]
parent = "Activités du lieu"
name = "Gestion de l'eau"
url = "/eau"

[[main]]
parent = "Activités du lieu"
name = "L'outil domotique"
url = "/domotique"

#[[main]]
#weight = 5
#name = "Blog"
#url = "/blog"

[[main]]
weight = 6
name = "Nous contacter"
url = "/contact"

# pied de page menu
[[footer]]
name = "À Propos"
url = "/about"
weight = 1

[[footer]]
name = "Vie privée"
url = "/privacy-policy"
weight = 2

[[footer]]
name = "Auteurs"
url = "/authors"
weight = 3

[[footer]]
name = "Nous contacter"
url = "/contact"
weight = 3

#[[footer]]
#name = "Elements"
#url = "/elements"
#weight = 4