# defaultContentLanguageInSubdir must be true for this to work.

#Other languages redirects
[[redirects]]
from = '/en/**'
to = '/en/404.en.html'
status = 404

# Default languages redirects (last)
[[redirects]]
from = '/**'
to = '/fr/404.fr.html'
status = 404
